```{r}
library(timereg)
```

```{r}
# generate artificial test dataset
n <- 500
u <- rnorm(n)
z <- rbinom(n,1,0.5)
a <- rnorm(n,3+z-u)
ti <- rexp(n,1/abs(0.5*a+0.25*u))
d <- ifelse(ti<10,1,0)
ti <- pmin(ti,10)
t0 <- runif(n,0,0.5)
id <- 1:length(a)
# vector of observed event times
times <- sort(unique(c(t0,ti)[t0<ti]))
n <- length(times)
```


```{r}
dataset <- data.frame(ti=rep(ti,each=n),t0=rep(t0,each=n),
d=rep(d,each=n),a=rep(a,each=n),z=rep(z,each=n),id=rep(id,each=n),
start=rep(c(0,times[-n]),length=n),stop=rep(times,length=n))
# Filter rows where t0 is less than ti
dataset <- dataset[dataset$t0<dataset$ti,]
# Filter rows where t0 is less than or equal to start
dataset <- dataset[dataset$t0<=dataset$start,]
# Filter rows where ti is greater than or equal to stop
dataset <- dataset[dataset$ti>=dataset$stop,]
# Set the values of d to 0 for rows where ti is greater than stop
dataset$d[dataset$ti>dataset$stop] <- 0
```

```{r}
# Add a new column 'm' to the dataset and initialize it to NULL
dataset$m <- NULL
for (i in 1:(length(times)-1)){
ty <- times[i]
s <- (dataset$ti >= ty)&(dataset$t0 <= ty)
# Use linear regression (lm) to predict values for 'a' based on 'z' 
# using data from the subset of the dataset
# Update the 'm' column for rows where 'start' is equal to the current time point
dataset$m[dataset$start==ty] <- predict(lm(a~z, data=dataset[s,]),
newdata=data.frame(z=dataset$z[dataset$start==ty]))
}
```
```{r}
aalen(Surv(start,stop,d)~const(m),data = dataset)
```

```{r}
res <- matrix(0,ncol=3,nrow=100)
delta <- resid(lm(a~z))
for (i in 1:100){
# choose a range of values theta up to the maximum accumulated exposure effect
# here an exposure effect of 0.08 which accumulates for at most 30 years
res[i,1] <- (30*i/100)*0.08
# calculate the correlation
res[i,2] <- cor(z,exp(-res[i,1]*delta))
# test for evidence of a correlation
res[i,3] <- cor.test(z,exp(-res[i,1]*delta))$p.value
}
par(mfrow=c(1,2))
plot(res[,1],res[,2],xlab=expression(theta),ylab="Correlation")
plot(res[,1],log(res[,3]),xlab=expression(theta),ylab="log p-value",
ylim=c(log(0.001),0))
abline(h=log(0.05))
```



